/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "About": "关于",
    "Defense:": "防御:",
    "Bonus time": "奖励时间",
    "Enable": "启用",
    "Help": "帮助",
    "Offense:": "攻击:",
    "Play": "开始",
    "Queue": "队列",
    "Restart Loop": "重启循环",
    "Ruins Exploration": "遗迹探索",
    "Simulant XP:": "模拟经验：",
    "Skills": "技能",
    "Stats": "统计",
    "Station Ruins": "车站遗址",
    "The wreckage of the station spins around you in silence. You were able to recover everybody's mindstate, but only barely. Humanity United attack ships still roam the area; your active camouflage will hide you, but you can't stay here forever. You have to get to Phobos-Deimos. You have to find someplace safe to store the consciousness of the hundreds of sentiences you protect. You have to get revenge.": "空间站的残骸静静地围绕着你旋转。 你能够恢复每个人的精神状态，但只是勉强。 人类联合攻击舰仍在该地区漫游； 你的主动伪装会隐藏你，但你不能永远留在这里。 你必须去 火卫一。 你必须找到一个安全的地方来储存你所保护的数百种意识的意识。 你必须报仇。",
    "Time": "时间",
    "Total time": "总时间",
    "Unspent Time": "未使用时间",
    "Vitals": "体征",
    "You need to enable JavaScript to run this\n        app.": "您需要启用JavaScript才能运行此应用程序。",
    "Awareness of the position of your chassis and other objects around you. Boosts defense.": "了解底盘和周围其他物体的位置。 增强防御。",
    "Awareness of your internal battery's charging characteristics. Increases energy gain from all sources.": "了解内置电池的充电特性。 增加从所有来源获得的能量。",
    "Communication with non-sentient electronic systems. Boosts actions involving hacking and similar things.": "与非感知电子系统的通信。 促进涉及黑客攻击和类似事情的行动。",
    "Current loadout insufficient for mission. Recommend recovering as much materiel as viable.": "当前负载不足以执行任务。 建议尽可能多地回收物资。",
    "Datalink": "数据链接",
    "Energy Transfer": "能量转移",
    "Ergodicity": "遍历性",
    "Explore Ruins": "探索废墟",
    "Increases amount of weapons and batteries that can be scavenged. 2.5x progress with Ship Hijacked.": "增加可以清除的武器和电池的数量。 Ship Hijacked 进度 2.5 倍。",
    "Lethality": "杀伤力",
    "Metacognition": "元认知",
    "Optimizing your own thinking. Increases XP gain for all skills, and trained whenever any other skill is trained.": "优化自己的思维。 增加所有技能的 XP 增益，并在训练任何其他技能时训练。",
    "Rewards": "奖励",
    "Ruins Exploration progress": "遗迹探索进度",
    "Spatial Awareness": "空间意识",
    "Trains": "火车",
    "You are a weapon as yet unforged. Hone yourself. Increases offense.": "你是尚未锻造的武器。 磨练自己。 增加进攻。",
    "Your ability to move randomly and to uncover the unknown. Boosts all progress-type skills (i.e., those that fill a meter to 100%).": "你随机移动和发现未知事物的能力。 提升所有进步型技能（即，那些将仪表填充到 100% 的技能）。",
    "Multiplies progress for Explore Ruins and Observe Patrol Routes by log2(1 + drones/4). The bonus is itself multiplied by log2(1 + datalink/64). Bonus stacks with Ship Hijacked bonuses.": "将探索废墟和观察巡逻路线的进度乘以 log2(1 + 无人机/4)。 奖励本身乘以 log2(1 + 数据链/64)。 奖励与飞创劫持奖励叠加。",
    "Intact Batteries": "完整的电池",
    "Link Sensor Drones": "链接传感器无人机",
    "Linked Sensor Drones": "链接传感器无人机",
    "Long-range sensors are still responding to pings. Superresolution routines loaded. Beginning handshake...": "远程传感器仍在响应 ping。 已加载超分辨率例程。 开始握手...",
    "Pause": "暂停",
    "Power source: located. Integration of power source will lead to loop extension.": "电源：位于。 集成电源会导致环路延长。",
    "Requires": "要求",
    "Scavenge Batteries": "清理电池",
    "Unlinked Sensor Drones": "未链接的传感器无人机",
    "[FAIL]": "[失败]",
    ". This is not a prestige. There is no backup": ". 这不是声望。 没有备份",
    ". This is not a prestige. There is no backup!": ". 这不是声望。 没有备份！",
    "Auto-restart": "自动重启",
    "Cheats": "作弊",
    "delete your entire save": "删除你的整个存档",
    "Enable cheats. This shows the rest of the cheat-mode settings and enables some extra actions. This will turn off autosaves since the developer uses it to debug; to manually save, just export your save and then immediately reimport.": "启用作弊。 这显示了作弊模式设置的其余部分并启用了一些额外的操作。 这将关闭自动保存，因为开发人员使用它进行调试； 要手动保存，只需导出您的保存，然后立即重新导入。",
    "Export Save": "导出存档",
    "Export/import save": "导出/导入 存档",
    "Hard Reset": "硬重置",
    "Import Save": "导入存档",
    "Pause on failure": "失败暂停",
    "Warning: This will": "警告：这将会",
    "Advance to the next zone. (NOTE: This is where the beta currently ends.)": "前进到下一个区域。 （注意：这是测试版目前结束的地方。）",
    "All multipliers to speed also apply a corresponding multiplier to your offense.": "所有速度乘数也会对您的进攻应用相应的乘数。",
    "Burst Clock α": "突发时钟α",
    "Burst Clock β": "突发时钟 β",
    "Capacitive Coupler": "电容耦合器",
    "Cognitive architect and synthetic neurologist.": "认知建筑师和合成神经学家。",
    "Combat": "战斗",
    "Combat Accelerator": "战斗加速器",
    "Command your autoforge systems to prepare to use any matter from future tasks to augment offensive capabilities. Any matter you already have will also be consumed.": "命令您的 autoforge 系统准备使用来自未来任务的任何材料来增强进攻能力。 任何你已经拥有的东西也会被消耗掉。",
    "Command your autoforge systems to prepare to use any matter from future tasks to restore HP. Any matter you already have will also be consumed.": "命令您的 autoforge 系统准备使用未来任务中的任何物质来恢复 HP。 任何你已经拥有的东西也会被消耗掉。",
    "Damage to chassis systems detected. Matter breakdown systems and repair systems online and functional.": "检测到底盘系统损坏。 物质故障系统和修复系统在线且功能正常。",
    "Discharge Teracapacitor": "放电太电容",
    "Dismantle Sensor Drones": "拆除传感器无人机",
    "Electrovore": "电泳",
    "Enkephalos": "脑脑病",
    "Ergon": "爱尔贡",
    "Functioning Teracapacitors": "功能强大的超级电容器",
    "Gives energy equal to 40% of the total energy spent in the loop, capped at 25600.": "提供等于循环中消耗的总能量的 40% 的能量，上限为 25600。",
    "Hack your stolen ship to bring the weapons, thrusters, and jump drive online.": "黑掉你偷来的船，让武器、推进器和跳跃引擎上线。",
    "Head engineer of the anticausal engine project.": "反因果引擎项目总工程师。",
    "Hijack Ship": "劫持船只",
    "Increases the energy cap of teracapacitors to 102400.": "将太极电容器的能量上限增加到 102400。",
    "Kill all remaining Preserver scouts": "杀死所有剩余的保护者侦察兵",
    "Kill one of the remaining Preserver scouts. Gives extra attempts at Disable Lockouts.": "杀死一名剩余的保护者侦察兵。 额外尝试禁用锁定。",
    "Kill Scout": "杀戮侦察兵",
    "Learn the patrol routes of the Presever cleanup crew.": "了解 Presever 清理人员的巡逻路线。",
    "LEAVE": "离开",
    "Leave Ruins": "离开废墟",
    "Matter": "物质",
    "Matter: Repair": "物质：维修",
    "Matter: Weaponry": "物质：武器",
    "Meta-metacognition": "元元认知",
    "Observe Patrol Routes": "观察巡逻路线",
    "Obtaining matter now also recharges your energy.": "现在获得物质也可以补充你的能量。",
    "Override Lockouts": "覆盖锁定",
    "Patrol Routes Observed": "观察到的巡逻路线",
    "Patrol Routes Observed progress": "巡逻路线观察到的进展",
    "Preserver materiel is not mechanically compatible with weapon systems, but can be used for parts.": "防护材料在机械上与武器系统不兼容，但可用作零件。",
    "Preserver Scouts Located": "找到保护者侦察兵",
    "Provides an increase in speed (and matching increase in energy consumption) for the first 16384 AEU of a loop.": "为循环的第一个 16384 AEU 提供速度增加（并相应增加能耗）。",
    "Provides an increase in speed (and matching increase in energy consumption) for the first 32768 AEU of a loop.": "为循环的第一个 32768 AEU 提供速度的增加（并相应地增加能量消耗）。",
    "QH Lockout Attempts": "QH 锁定尝试",
    "QH-283 lockouts have been disabled. Jump drive ready and online. There's nothing for you here any more.": "QH-283 锁定已被禁用。 跳跃驱动准备就绪并在线。 这里再也没有适合你的东西了。",
    "QH-283 lockouts must be disabled before the jump drive engages. Anti-brute-force mechanisms prevent repeated attacks. Recommened attempting over multiple temporal iterations.": "在跳跃驱动器接合之前，必须禁用 QH-283 锁定装置。 反暴力破解机制防止重复攻击。 建议尝试多次时间迭代。",
    "Self-Optimization": "自我优化",
    "Ship appears to contain Sixteenth Flower hardware with personality decompression routines.": "飞船似乎包含带有个性减压程序的第十六花硬件。",
    "Ship Lockout Disabled": "禁用船舶锁定",
    "Ship Lockout Disabled progress": "船舶锁定禁用进度",
    "Simulant": "模拟物",
    "Simulations predict >99.99% kill rate with minimal retaliatory damage.": "模拟预测 >99.99% 的杀伤率和最小的报复性伤害。",
    "Specialist in ultra-high-density energy storage and transport.": "超高密度储能与传输专家。",
    "Strafing Run": "扫射跑",
    "Surviving Preserver forces may alert superiors. They cannot be allowed to live.": "幸存的保护者部队可能会提醒上级。 不能让他们活着。",
    "Tactical planning substrate suggests attacking during moments of isolation.": "战术规划基础建议在孤立的时刻进行攻击。",
    "Target spotted: Humanity United patrol vessel QH-283 appears to be separated from the rest. Simulations indicate hijack possible.": "发现目标：人类联合巡逻舰 QH-283 似乎与其他船只分开。 模拟表明劫持是可能的。",
    "Tekhne": "技术",
    "Teracapacitor integrity critical. Attempting repair; however, discharge is likely to destroy charging circuits. Recommend delaying their use.": "Teracapacitor 完整性至关重要。 尝试修复； 但是，放电可能会破坏充电电路。 建议延迟使用。",
    "The cost of all non-combat tasks decreases the more time you've spent across all loops.": "您在所有循环中花费的时间越多，所有非战斗任务的成本就会降低。",
    "There is nothing left for them to monitor. The Sixteenth Flower is gone.": "他们没有什么可以监视的了。 第十六朵花不见了。",
    "Unlock Simulant": "解锁模拟器",
    "Unlocks the simulant subsystem, allowing you to permanently upgrade your mind.": "解锁模拟子系统，让你永久升级你的思想。",
    "Use your stolen ship to fly to your sensor drone array. Each drone dismantled provides 3000 AEU.": "使用你偷来的船飞到你的传感器无人机阵列。 拆除的每架无人机提供 3000 AEU。",
    "Your metacognition level is treated as if it was multiplied by its square root.": "您的元认知水平被视为乘以其平方根。",
    "Adds the Ship Hijacked flag, increasing rate of exploration.": "添加船舶劫持标志，增加探索速度。",
    "The simulant system allows you to effectively run some aspects of your teammates' personality. Once you've unlocked it, you get simulant XP at a rate of 1 per second. You can spend simulant XP to unlock subroutines, which are permanent buffs that persist across all loops. Hovering over a subroutine will tell you its effects. Note that subroutine XP is not refundable!": "模拟系统可以让你有效地运行队友个性的某些方面。 解锁后，您将以每秒 1 的速度获得模拟 XP。 您可以花费模拟 XP 来解锁子程序，这些子程序是在所有循环中持续存在的永久增益。 将鼠标悬停在子例程上会告诉您它的效果。 请注意，子程序 XP 不可退还！",
    "The effect of the armor multiplier is that if your offense is near the target's defense (or vice versa), your damage is significantly cut. For example, against a target with 100 defense, if your offense is 100 then you'll only do 35 damage, but if your offense is 300 then you'll deal about 194 damage.": "护甲倍增器的效果是，如果你的进攻接近目标的防御（反之亦然），你的伤害就会大大减少。 例如，对于一个防御力为 100 的目标，如果您的攻击力为 100，那么您只会造成 35 点伤害，但如果您的攻击力为 300 点，那么您将造成大约 194 点伤害。",
    "The queue panel is the main interface for playing the game. On the left is the list of tasks that you want to execute; on the right is the tasks you're executing. You can't change tasks mid-loop; any changes will apply at the start of the next loop. You can add tasks to the queue using the buttons at the bottom and reorder them using the buttons next to each entry in the task queue.": "队列面板是玩游戏的主要界面。 左侧是您要执行的任务列表； 右侧是您正在执行的任务。 您不能在循环中更改任务； 任何更改都将在下一个循环开始时应用。 您可以使用底部的按钮将任务添加到队列中，并使用任务队列中每个条目旁边的按钮将它们重新排序。",
    "damage to each other each second. If the task reaches 0 HP, you succeed; if you reach 0 HP, the loop restarts, even if the task reaches 0 HP on the same game update. Note that combat tasks still use energy as well!": "每秒互相伤害。 如果任务达到 0 HP，则您成功； 如果您达到 0 HP，循环将重新开始，即使任务在同一游戏更新中达到 0 HP。 请注意，战斗任务仍然会消耗能量！",
    "Aion is meant to be a self-sustaining weapons platform. Matter represents its ability to break down its opponents and their gear. Certain tasks will give matter as a reward;": "Aion 旨在成为一个自我维持的武器平台。 物质代表它分解对手及其装备的能力。 某些任务会给予物质作为奖励；",
    "and": "和",
    "armorMultiplier = offense / (offense + defense)^2": "护甲 攻击/（攻击+防御）^2",
    "Certain tasks are 'combat' tasks, which represent Aion fighting someone or something. You and your opponent simultaneously deal": "某些任务是“战斗”任务，代表永恒之塔与某人或某物战斗。 你和你的对手同时发牌",
    "damage to each other per second, where": "每秒对彼此造成的伤害，其中",
    "file a bug": "提交错误",
    "How to Play": "怎么玩",
    "If nothing is happening, try hitting the play/pause button and the 'restart loop' button on the left hand panel. If things are behaving unexpectedly, please": "如果没有任何反应，请尝试点击播放/暂停按钮和左侧面板上的“重启循环”按钮。 如果事情表现出乎意料，请",
    "Most actions will give you some amount of XP in a skill. Getting a skill from level N - 1 to level N takes": "大多数操作都会为您提供一定数量的技能 XP。 将一项技能从 N - 1 级提升到 N 级需要",
    "N * 1024": "N * 1024",
    "offense * armorMultiplier": "进攻*护甲倍数",
    "or talk to me on Discord!": "或在 Discord 上与我交谈！",
    "will control how Aion uses matter.": "将控制永恒之塔如何使用物质。",
    "wrtsc is a time-loop idle game. If you've played any variation of Idle Loops, the basic gameplay is basically the same.": "wrtsc 是一款时间循环闲置游戏。 如果您玩过 Idle Loops 的任何变体，基本的游戏玩法基本相同。",
    "XP, so skills will level slower as you go. Hover over a skill name in the player panel to see what it does.": "XP，所以技能会随着你的进步而变慢。 将鼠标悬停在播放器面板中的技能名称上以查看它的作用。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "XPL_RUIN": "XPL_RUIN",
    "SCAV_BAT": "SCAV_BAT",
    "LINK_DRN": "LINK_DRN",
    "OBS_PTRL": "OBS_PTRL",
    "MAT_WEPN": "MAT_WEPN",
    "MAT_REP": "MAT_REP",
    "KILL_SCT": "KILL_SCT",
    "OVR_LOCK": "OVR_LOCK",
    "STRAF_RN": "STRAF_RN",
    "UNLOK_SM": "UNLOK_SM",
    "HJCK_SHP": "HJCK_SHP",
    "DSMN_DRN": "DSMN_DRN",
    "DIS_TERA": "DIS_TERA",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)ms$/,
    /^\(([\d\.]+)\)$/,
    /^\[  ([\d\.]+)\%\]$/,
    /^\[ ([\d\.]+)\%\]$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)s$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)\% Ruins Exploration$/, '$1% 遗迹探索'],
    [/^([\d\.]+)\% Ship Lockout Disabled$/, '$1% 飞船锁定已禁用'],
    [/^([\d\.]+)\% Patrol Routes Observed$/, '$1% 巡逻路线观察'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/, '$1小时 $2分 $3秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Ergodicity XP$/, '$1 遍历经验'],
    [/^([\d\.,]+) Datalink XP$/, '$1 数据链经验'],
    [/^([\d\.,]+) Energy Transfer XP$/, '$1 能量转移经验'],
    [/^([\d\.,]+) Spatial Awareness XP$/, '$1 空间意识经验'],
    [/^([\d\.,]+)x Unlinked Sensor Drones$/, '$1x 未链接的传感器无人机'],
    [/^([\d\.,]+)x Linked Sensor Drones$/, '$1x 已链接的传感器无人机'],
    [/^([\d\.,]+)x Intact Batteries$/, '$1x 完整的电池'],
    [/^([\d\.,]+)x QH Lockout Attempts$/, '$1x QH 锁定尝试'],
    [/^([\d\.,]+)x Preserver Scouts Located$/, '$1x 找到保护者侦察兵'],
    [/^([\d\.,]+)x QH Lockout Attempts$/, '$1x QH 锁定尝试'],
    [/^([\d\.,]+)x Matter$/, '$1x 物质'],
    [/^([\d\.,]+)x Functioning Teracapacitors$/, '$1x 功能强大的超级电容器'],
    [/^Increases energy by ([\d\.,]+).$/, '提高能量 $1。'],
    [/^([\d\.,]+) Lethality XP$/, '$1 杀伤力经验'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Lethality XP, ([\d\.,]+) Spatial Awareness XP$/, '$1 杀伤力经验，$2 空间感知经验'],
    [/^([\d\.,]+) Energy Transfer XP, 64 Datalink XP$/, '$1 能量传输经验，$2 数据链经验'],
    [/^([\d\.,]+) offense, ([\d\.,]+) defense, ([\d\.,]+) HP$/, '$1 攻击，$2 防御，$3 生命值'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);