/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "About": "关于",
    "Defense:": "防御:",
    "Bonus time": "奖励时间",
    "Enable": "启用",
    "Help": "帮助",
    "Offense:": "罪行:",
    "Play": "开始",
    "Queue": "队列",
    "Restart Loop": "重启循环",
    "Ruins Exploration": "遗迹探索",
    "Simulant XP:": "模拟经验：",
    "Skills": "技能",
    "Stats": "统计",
    "Station Ruins": "车站遗址",
    "The wreckage of the station spins around you in silence. You were able to recover everybody's mindstate, but only barely. Humanity United attack ships still roam the area; your active camouflage will hide you, but you can't stay here forever. You have to get to Phobos-Deimos. You have to find someplace safe to store the consciousness of the hundreds of sentiences you protect. You have to get revenge.": "空间站的残骸静静地围绕着你旋转。 你能够恢复每个人的精神状态，但只是勉强。 人类联合攻击舰仍在该地区漫游； 你的主动伪装会隐藏你，但你不能永远留在这里。 你必须去 火卫一。 你必须找到一个安全的地方来储存你所保护的数百种意识的意识。 你必须报仇。",
    "Time": "时间",
    "Total time": "总时间",
    "Unspent Time": "未使用时间",
    "Vitals": "体征",
    "You need to enable JavaScript to run this\n        app.": "您需要启用JavaScript才能运行此应用程序。",
    "Awareness of the position of your chassis and other objects around you. Boosts defense.": "了解底盘和周围其他物体的位置。 增强防御。",
    "Awareness of your internal battery's charging characteristics. Increases energy gain from all sources.": "了解内置电池的充电特性。 增加从所有来源获得的能量。",
    "Communication with non-sentient electronic systems. Boosts actions involving hacking and similar things.": "与非感知电子系统的通信。 促进涉及黑客攻击和类似事情的行动。",
    "Current loadout insufficient for mission. Recommend recovering as much materiel as viable.": "当前负载不足以执行任务。 建议尽可能多地回收物资。",
    "Datalink": "数据链接",
    "Energy Transfer": "能量转移",
    "Ergodicity": "遍历性",
    "Explore Ruins": "探索废墟",
    "Increases amount of weapons and batteries that can be scavenged. 2.5x progress with Ship Hijacked.": "增加可以清除的武器和电池的数量。 Ship Hijacked 进度 2.5 倍。",
    "Lethality": "杀伤力",
    "Metacognition": "元认知",
    "Optimizing your own thinking. Increases XP gain for all skills, and trained whenever any other skill is trained.": "优化自己的思维。 增加所有技能的 XP 增益，并在训练任何其他技能时训练。",
    "Rewards": "奖励",
    "Ruins Exploration progress": "遗迹探索进度",
    "Spatial Awareness": "空间意识",
    "Trains": "火车",
    "You are a weapon as yet unforged. Hone yourself. Increases offense.": "你是尚未锻造的武器。 磨练自己。 增加进攻。",
    "Your ability to move randomly and to uncover the unknown. Boosts all progress-type skills (i.e., those that fill a meter to 100%).": "你随机移动和发现未知事物的能力。 提升所有进步型技能（即，那些将仪表填充到 100% 的技能）。",
    "Multiplies progress for Explore Ruins and Observe Patrol Routes by log2(1 + drones/4). The bonus is itself multiplied by log2(1 + datalink/64). Bonus stacks with Ship Hijacked bonuses.": "将探索废墟和观察巡逻路线的进度乘以 log2(1 + 无人机/4)。 奖励本身乘以 log2(1 + 数据链/64)。 奖励与飞创劫持奖励叠加。",
    "Intact Batteries": "完整的电池",
    "Link Sensor Drones": "链接传感器无人机",
    "Linked Sensor Drones": "链接传感器无人机",
    "Long-range sensors are still responding to pings. Superresolution routines loaded. Beginning handshake...": "远程传感器仍在响应 ping。 已加载超分辨率例程。 开始握手...",
    "Pause": "暂停",
    "Power source: located. Integration of power source will lead to loop extension.": "电源：位于。 集成电源会导致环路延长。",
    "Requires": "要求",
    "Scavenge Batteries": "清理电池",
    "Unlinked Sensor Drones": "未链接的传感器无人机",
    "[FAIL]": "[失败]",
    ". This is not a prestige. There is no backup": ". 这不是声望。 没有备份",
    ". This is not a prestige. There is no backup!": ". 这不是声望。 没有备份！",
    "Auto-restart": "自动重启",
    "Cheats": "作弊",
    "delete your entire save": "删除你的整个存档",
    "Enable cheats. This shows the rest of the cheat-mode settings and enables some extra actions. This will turn off autosaves since the developer uses it to debug; to manually save, just export your save and then immediately reimport.": "启用作弊。 这显示了作弊模式设置的其余部分并启用了一些额外的操作。 这将关闭自动保存，因为开发人员使用它进行调试； 要手动保存，只需导出您的保存，然后立即重新导入。",
    "Export Save": "导出存档",
    "Export/import save": "导出/导入 存档",
    "Hard Reset": "硬重置",
    "Import Save": "导入存档",
    "Pause on failure": "失败暂停",
    "Warning: This will": "警告：这将会",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "XPL_RUIN": "XPL_RUIN",
    "SCAV_BAT": "SCAV_BAT",
    "LINK_DRN": "LINK_DRN",
    "OBS_PTRL": "OBS_PTRL",
    "MAT_WEPN": "MAT_WEPN",
    "MAT_REP": "MAT_REP",
    "KILL_SCT": "KILL_SCT",
    "OVR_LOCK": "OVR_LOCK",
    "STRAF_RN": "STRAF_RN",
    "UNLOK_SM": "UNLOK_SM",
    "HJCK_SHP": "HJCK_SHP",
    "DSMN_DRN": "DSMN_DRN",
    "DIS_TERA": "DIS_TERA",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)ms$/,
    /^\(([\d\.]+)\)$/,
    /^\[  ([\d\.]+)\%\]$/,
    /^\[ ([\d\.]+)\%\]$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)\% Ruins Exploration$/, '$1% 遗迹探索'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/, '$1小时 $2分 $3秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Ergodicity XP$/, '$1 遍历经验'],
    [/^([\d\.,]+) Datalink XP$/, '$1 数据链经验'],
    [/^([\d\.,]+) Energy Transfer XP$/, '$1 能量转移经验'],
    [/^([\d\.,]+)x Unlinked Sensor Drones$/, '$1x 未链接的传感器无人机'],
    [/^([\d\.,]+)x Linked Sensor Drones$/, '$1x 已链接的传感器无人机'],
    [/^([\d\.,]+)x Intact Batteries$/, '$1x 完整的电池'],
    [/^([\d\.,]+)x Matter$/, '$1x 物质'],
    [/^([\d\.,]+)x Functioning Teracapacitors$/, '$1x 功能强大的超级电容器'],
    [/^Increases energy by ([\d\.,]+).$/, '提高能量 $1。'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);